In [4]:
import pandas as pd
import matplotlib.pyplot as plb
import numpy as np

Khoi tao numby

In [5]:
x= np.array([1,2,3])
print(x)
print(x.shape)
print(x.size)
print(x[1])

[1 2 3]
(3,)
3
2


In [6]:
y = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]]) 
print(y)
print(y.shape)
print(type(y))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
<class 'numpy.ndarray'>


#KHOI TAO MANG HAI CHIEU 

In [ ]:
h = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(h[0,4])