In [15]:
import pandas as pd
import matplotlib.pyplot as plb
import numpy as np

Khoi tao numby


In [16]:
x= np.array([1,2,3])
print(x)

[1 2 3]


In [17]:
print(x.shape)

(3,)


In [18]:
print(x.size)


3


In [19]:
y = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]]) 
print(y)
print(type(y))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
