In [1]:
import numpy as np


Cac mang dac biet

In [32]:
#Mang 0
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [33]:
#Mang toan mot
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
#Ma tran don vi
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
#Tao day so
a=np.arange(0,20,1)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [36]:
#Tao n so cach deu tu start den end
a=np.linspace(0,1,10)
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [37]:
#Tao mang ngau nhien trong nua khoang [0,1)
a=np.random.rand(5,6)
print(a)

[[0.70297129 0.88655272 0.86557546 0.23907494 0.77498747 0.4900029 ]
 [0.33538653 0.92894972 0.08208896 0.30639079 0.11179605 0.81340739]
 [0.84506764 0.99371704 0.18633094 0.60863815 0.47423847 0.32094225]
 [0.50447637 0.07166459 0.04708035 0.92917657 0.67916686 0.39171803]
 [0.28645175 0.05072243 0.13778947 0.60602117 0.38635042 0.45417571]]


In [38]:
#Tao mang ngau nhien trong nua khoang [a,b)
a=5
b=10
x=np.random.uniform(a,b,size=(2,3))
print(x)
#C2
x2= a+(b-a)*np.random.rand(2,3)
print(x2)

[[8.99078782 9.12907597 5.7757246 ]
 [6.38983635 9.69883914 8.22637272]]
[[5.76877341 5.13779612 7.19180547]
 [7.57128912 6.73064274 5.31201944]]


#Mot so thuc tinh cua mang

In [39]:
x=np.array([[1,'tung',3],[4,5,6]])
print(x.shape)#kich thuoc mang
print(x.ndim)#so chieu
print(x.size) # so phan tu
print(x.dtype)#Kieu du lieu cua array

(2, 3)
2
6
<U21


#Truy cao vao array

In [40]:
a=np.array([[1,2,3],[4,5,6]])
print(a[0,1])
print(a[:,2])
print(a[0,:])

2
[3 6]
[1 2 3]


#Cac phep toan giua hai ma tran

In [41]:
a=np.array([[1,2],
            [4,5]])
b=np.array([[6,7],
            [7,8]])
print(a+b)
print(a-b)
print(a*b)
print(a@b)
print(np.matmul(a,b))
print(a/b)


[[ 7  9]
 [11 13]]
[[-5 -5]
 [-3 -3]]
[[ 6 14]
 [28 40]]
[[20 23]
 [59 68]]
[[20 23]
 [59 68]]
[[0.16666667 0.28571429]
 [0.57142857 0.625     ]]


#Thay doi hinh dang ma tran

In [47]:
a=np.array([[1,2,3],
            [4,5,6]])
x=a.reshape(3,2)
print(x)
y=a.flatten()
print(y)
z=a.T
print(z)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
