In [55]:
import numpy as np


Cac mang dac biet

In [56]:
#Mang 0
a=np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [57]:
#Mang toan mot
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [58]:
#Ma tran don vi
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [59]:
#Tao day so
a=np.arange(0,20,1)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [60]:
#Tao n so cach deu tu start den end
a=np.linspace(0,1,10)
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [61]:
#Tao mang ngau nhien trong nua khoang [0,1)
a=np.random.rand(5,6)
print(a)

[[0.49555876 0.12172913 0.60813799 0.23278408 0.43996342 0.37044775]
 [0.7825227  0.90581911 0.07881185 0.11675138 0.08172768 0.57003452]
 [0.13641583 0.40496004 0.35136366 0.31979846 0.64075255 0.33714587]
 [0.8935163  0.48272678 0.65699717 0.36899827 0.53474834 0.73257721]
 [0.33132922 0.23349744 0.49511464 0.74006059 0.51914688 0.49326304]]


In [62]:
#Tao mang ngau nhien trong nua khoang [a,b)
a=5
b=10
x=np.random.uniform(a,b,size=(2,3))
print(x)
#C2
x2= a+(b-a)*np.random.rand(2,3)
print(x2)

[[8.58112456 9.57673887 7.45347049]
 [7.7680331  8.07777324 8.49016359]]
[[8.81170658 9.7130867  8.85760451]
 [6.6703358  8.4169283  7.55076391]]


#Mot so thuc tinh cua mang

In [63]:
x=np.array([[1,'tung',3],[4,5,6]])
print(x.shape)#kich thuoc mang
print(x.ndim)#so chieu
print(x.size) # so phan tu
print(x.dtype)#Kieu du lieu cua array

(2, 3)
2
6
<U21


#Truy cao vao array

In [64]:
a=np.array([[1,2,3],[4,5,6]])
print(a[0,1])
print(a[:,2])
print(a[0,:])

2
[3 6]
[1 2 3]


#Cac phep toan giua hai ma tran

In [65]:
a=np.array([[1,2],
            [4,5]])
b=np.array([[6,7],
            [7,8]])
print(a+b)
print(a-b)
print(a*b)
print(a@b)
print(np.matmul(a,b))
print(a/b)


[[ 7  9]
 [11 13]]
[[-5 -5]
 [-3 -3]]
[[ 6 14]
 [28 40]]
[[20 23]
 [59 68]]
[[20 23]
 [59 68]]
[[0.16666667 0.28571429]
 [0.57142857 0.625     ]]
