#Bai1

In [2]:
import numpy as np
a= np.arange(0,10,1)
print(a)
print(f"Kieu du lieu cua mang a la: {a.dtype} va co tong {np.sum(a)}")

[0 1 2 3 4 5 6 7 8 9]
Kieu du lieu cua mang a la: int64 va co tong 45


#bai2

In [3]:
b=np.arange(1,10,1)
b=b.reshape(3,3)
print(b)
print(f"Kieu du lieu cua mang b la {b.dtype}")
print(b[0,:])
print(np.sum(b,axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Kieu du lieu cua mang b la int64
[1 2 3]
[12 15 18]


In [4]:
x = np.zeros((3,4))
print(x)
x=np.eye(5)
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
x=np.random.rand(1,10)
print(x)


[[0.10416031 0.48598053 0.46449598 0.45529658 0.19967413 0.42218984
  0.64621982 0.71648443 0.37629034 0.22748862]]


In [6]:
x =  np.arange(1,13,1)
x = x.reshape(3,4)
print(x)
x=x.reshape(4,-1) # Tu dieu chinh so hang/cot duoc dat la -1
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#Chuan cua vecto

In [7]:
a = np.arange(1,10)
x = np.linalg.norm(a,ord = 1) # L1 norm
y = np.linalg.norm(a,ord = 2) # l2 norm
z = np.linalg.norm(a,ord= np.inf) #L3 norm
print(x)
print(y)
print(z)

45.0
16.881943016134134
9.0


###Dinh thuc cua ma tran

In [8]:
a = np.arange(1,10).reshape(3,3)
print(a)
dt = a[0,0]*a[1,1]*a[2,2] + a[1,0]*a[2,1]*a[0,2]+a[0,1]*a[1,2]*a[2,0] - a[0,2]*a[1,1]*a[2,0]-a[1,2]*a[2,1]*a[0,0] - a[0,1]*a[1,0]*a[2,2]
dt2 = np.linalg.det(a)
print(f"{dt} {dt2}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0 0.0


#Ma tran nghich dao

In [9]:
a = np.arange(1,5).reshape(2,2)
dt = np.linalg.det(a)
print(f"Dinh thuc cua ma tra a la {dt}")
akn = np.linalg.inv(a)
print(f"Ma tran nghich dao cua ma tran a la {akn}")

Dinh thuc cua ma tra a la -2.0000000000000004
Ma tran nghich dao cua ma tran a la [[-2.   1. ]
 [ 1.5 -0.5]]


#Broadcasting

In [10]:
a = np.array([10,10,10])
b=np.arange(1,10).reshape(3,3)
print(f"Ket cua cua broadcasting ma tran \n {a}\n{b}\n{a+b}")

Ket cua cua broadcasting ma tran 
 [10 10 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


#Tao ma tran duong cheo tu vecto [1,2,3,4]

In [11]:
a = np.array([1,2,3,4])
b = np.eye(len(a))
for i in range(len(a)):
    b[i,i] = a[i]
print(b)
print(np.diag(a))

[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#Phep so sanh giua hai ma tran

In [12]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a == b) 

[ True  True  True  True]


In [15]:
a = np.random.uniform(1,10,size = (3,3))
a[a > 5] = 0
print(a)
print(np.trace(a))

[[0.         2.10520968 1.85430936]
 [0.         3.73875724 3.93936013]
 [2.84939975 3.37460858 0.        ]]
3.738757244447942


In [17]:
a = np.arange(1,13).reshape(3,4)
print(a)
for i in range(len(a)):
    print(sum(a[i,:]/len(a[i,:])))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2.5
6.5
10.5
